spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/fitness_club_db
    username: postgres
    password: password
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true